# docker-compose down -v --remove-orphans # --rmi all
# docker-compose up --force-recreate --build

version: '3'

networks:
  default:
  backend:
    internal: true

services:
  recode_db:
    container_name:
      recode_db
    image:
      library/mariadb:10
    restart:
      always
    environment:
      - MYSQL_ROOT_PASSWORD=recode123
      - MYSQL_DATABASE=vit
      - MYSQL_USER=recode
      - MYSQL_PASSWORD=recode123
      # - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - /opt/docker/mariadb/conf.d:/etc/mysql/conf.d
      - /opt/docker/mariadb/datadir:/var/lib/mysql
    networks:
      - backend

  recode:
    container_name:
      recode
    image:
      recode:1.0
    build:
      ./recode
    restart:
      always
    ports:
      - 8081:8081/tcp
    environment:
      - MYSQL_HOST=recode_db
      - MYSQL_ROOT_PASSWORD=recode123
      - MYSQL_DATABASE=vit
      - MYSQL_USER=root
      - MYSQL_PASSWORD=recode123
    volumes:
      - /opt/docker/recode:/home/recode
    depends_on:
      - recode_db
    networks:
      - default
      - backend
